source("00_download/download_announcements.R", verbose = TRUE, echo = TRUE)
source("00_download/download_quizzes.R", verbose = TRUE, echo = TRUE)
source("00_download/download_media.R", verbose = TRUE, echo = TRUE)
source("00_download/download_files.R", verbose = TRUE, echo = TRUE)
source("00_download/download_enrollments.R", verbose = TRUE, echo = TRUE)
source("00_download/download_pages.R", verbose = TRUE, echo = TRUE)
source("00_download/download_modules.R", verbose = TRUE, echo = TRUE)
source("00_download/download_assignments.R", verbose = TRUE, echo = TRUE)
source("00_download/download_assignment_data.R", verbose = TRUE, echo = TRUE)
source("00_download/download_course_participation.R", verbose = TRUE, echo = TRUE)
source("00_download/download_course_student_summaries.R", verbose = TRUE, echo = TRUE)
source("00_download/download_powerpoint_text.R", verbose = TRUE, echo = TRUE)
source("00_download/download_pdf_text.R", verbose = TRUE, echo = TRUE)

source("00_download/download_calender_events.R", verbose = TRUE, echo = TRUE)
source("00_download/download_student_assignments.R", verbose = TRUE, echo = TRUE)
